language: python
sudo: true
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
# Global configs cause unit tests to break.
# Issue: travis-ci/travis-ci#5246
env:
  - BOTO_CONFIG=/tmp/fake
os:
  - linux
# Python 2.6 uses a backported version of unittest.
# Python 3.2 does not have mock installed by default.
install:
  - pip install boto
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip3.2 install mock; fi
# nosetests will run all tests within the current directory.
script:
  - nosetests

deploy:
  provider: pypi
  user: gc-team
  password:
    secure: ljO08Dm8MnVZLse68cxe/o85x20C3JseBupESr2hXK/3axRYbW3o6TbRwAlHDCrOrDjg+NzmEjZojxg9A2+5DuWcWJLvKcCG4NbheoMAbs38IGou5mAbLhcj+GBdM03wKHqEDPEyMT5s/LuMlpOcxtDnF+oJ0Wm8czGnyi06IM4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: GoogleCloudPlatform/compute-image-packages
